### PR TITLE
Milestone 6 Friendships V2

### PR DESCRIPTION
**Pull request by s0kil**
- Added Mutual Friendship Specs
- Friendship Validations, So Friendship cannot consist of User being the Friend

NOTE FOR TSE'S: We created this project with the Instagram follow relationships in mind, this means that it is a two-way friendship where if user A wants to see user B's post, user A has to request friendship to user B, if user B accepts it, user A will be able to see user B's post in his/hers timeline but user B won't be able to see user A's post unless he does the same thing, send a friendship request and gets accepted by user A.

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
 - [x] For `timeline_post` you could refactor it to this and everything connected with data processing should be encapsulated in models and used in controllers, lets move this method
````ruby
def timeline_post
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end

````
* [x] User#confirmed_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

* [x] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

* [x] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```
- [x] Let's write integration and a proper unit test using Rspec
- [x] The friend request button should disappear once accepted.
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
-  [x] When a request is sent the button(SEND FRIEND REQUEST) should disappear, once the request has been accepted then the Unfriend button can show up, else if rejected then you can display SEND FRIEND REQUEST button. 
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by s0kil** [comment]
We have implemented an Instagram style following, both users need to send a request to form a mutual relationship.
Please refer to https://github.com/danielsokil/social-media/pull/5 for more information.

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @s0kil and @e71az  :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
