### PR TITLE
Milestone One Complete

### PR DESCRIPTION
**Pull request by s0kil**
- Prepared data architecture documentation
- DB Tables For: `user`, `relationship`, `post`, `comment`, `like`

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @s0kil and @e71az, great job with this project :+1: However, there are some comments we need to address :100: Kindly check the comments below:
- `ERD Diagram`
  - `Post model` is missing the `user_id` field. Which should be an FK in the post model
  - `Like model` let us add `ID` field to the like model, also let us remove the PK on the `user_id` and `post_id`
  - `Relationship model` let us remove the PK on the `user_id` and `following_id`. Kindly change the `following_id` to `friend_id`. Also, we could rename the `Relationship model` to `Friendship model`

Kindly implement these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by s0kil** [comment]
We added the `PK, FK`to multiple tables to show that both will be combined to create the CP (compound key).

**Comment by eliasecasta** [comment]
> ## Status: Require changes ♻️ 🚥
> Hi @s0kil and @e71az, great job with this project 👍 However, there are some comments we need to address 💯 Kindly check the comments below:
> 
> * `ERD Diagram`
>   
>   * `Post model` is missing the `user_id` field. Which should be an FK in the post model
>   * `Like model` let us add `ID` field to the like model, also let us remove the PK on the `user_id` and `post_id`
>   * `Relationship model` let us remove the PK on the `user_id` and `following_id`. Kindly change the `following_id` to `friend_id`. Also, we could rename the `Relationship model` to `Friendship model`
> 
> Kindly implement these changes and submit another code review 😄
> _Happy coding_ 👨‍💻
> [Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

We created those tables with the composite keys option into account, what should we do in this case? Following this youtube video he didn't need to use the primary key: https://www.youtube.com/watch?v=-CuY5ADwn24&ab_channel=Lucidchart

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### You have done well so far :clap: However, you have a few issues to fix:-
- [x] Rename the table relationship to friendship
- [x] Like -> id, user_id, post_id
- [x] Friendship -> id, user_id, friend_id, status
- [x] User -> id, name, image_link
- [x] Post -> id, user_id, content
- [x] Comment -> id, user_id, post_id, content
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by s0kil** [comment]
> Hello Team
> 
> ### You have done well so far  However, you have a few issues to fix:-
> * [x]  Rename the table relationship to friendship
> * [x]  Like -> id, user_id, post_id
> * [x]  Friendship -> id, user_id, friend_id, status
> * [x]  User -> id, name, image_link
> * [x]  Post -> id, user_id, content
> * [x]  Comment -> id, user_id, post_id, content
> 
> ### Make the changes and submit for another code review. Good luck.
> * Happy coding!

It seems you did not review the project, that changes you requested have been addressed.

**Comment by s0kil** [comment]
> * Like -> id, user_id, post_id

In the Like table, since we have both `user_id` and `post_id` as foreign keys, we do not need an `id` field, instead both `user_id` and `post_id` will be combined automatically to create the composite key.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### You got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
